// <auto-generated />
using Eroski.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eroski.Migrations
{
    [DbContext(typeof(EroskiContext))]
    [Migration("20211220092709_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Eroski.Eroski", b =>
                {
                    b.Property<string>("seccion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ticket")
                        .HasColumnType("int");

                    b.HasKey("seccion");

                    b.ToTable("Eroski");
                });
#pragma warning restore 612, 618
        }
    }
}
